
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_do_chef
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:
  paths-to-match:
    - /api/v1/**
  swagger-ui:
    use-root-path: true
